// src/components/interactive/BackToTop.tsx
import Icon from "@components/shared/Icon";
import { useEffect, useState } from "preact/hooks";

function BackToTop() {
  const [isHidden, setIsHidden] = useState(true);

  useEffect(() => {
    const startSection = document.querySelector("#start");
    if (!startSection) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          setIsHidden(entry.isIntersecting);
        });
      },
      { threshold: 0.99 },
    );

    observer.observe(startSection);
    return () => observer.disconnect();
  }, []);

  return (
    <a
      id="back-to-top-shortcut"
      class="push-down fixed bottom-8 right-6 p-2 text-2xl text-white transition-visibility-transform duration-300 ease-out hover:text-orchid aria-hidden:invisible aria-hidden:translate-y-full aria-hidden:opacity-0 md:right-12"
      href="#start"
      aria-label="Voltar ao início"
      aria-hidden={isHidden}
    >
      <Icon name="back-to-top" />
    </a>
  );
}

export default BackToTop;

// src/lib/components/BackToTop.svelte
<script lang="ts">
  import Icon from "$lib/components/Icon.svelte";
  import { onMount } from "svelte";

  let hidden = $state(true);

  onMount(() => {
    const startSection = document.querySelector("#start");
    if (!startSection) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          hidden = entry.isIntersecting;
        });
      },
      { threshold: 0.99 },
    );

    observer.observe(startSection);
    return () => {
      observer.disconnect();
    };
  });
</script>

<a
  class="push-on-active tablet:right-12 tablet:bottom-16 desktop:right-16 hover:text-orchid text-offwhite fixed bottom-8 right-6 duration-300 ease-out aria-hidden:invisible aria-hidden:translate-y-full aria-hidden:opacity-0 motion-safe:transition-[visibility,opacity,translate,scale]"
  href="#start"
  aria-label="Voltar ao início"
  aria-hidden={hidden}
>
  <Icon class="size-8" name="back-to-top" />
</a>
