// src/components/interactive/Carousel.tsx
import type { ImageMetadata } from "astro";
import { useMemo, useState } from "preact/hooks";
import { simpleCX } from "../../utils/cx";
import Icon from "../shared/Icon";

export type CarouselProps = {
  slides: ImageMetadata[];
};

function Carousel({ slides }: CarouselProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const lastSlide = useMemo(() => slides.length - 1, [slides]);

  const goToSlide = (i: number) => {
    setCurrentSlide(i > lastSlide ? 0 : i < 0 ? lastSlide : i);
  };
  const nextSlide = () => {
    goToSlide(currentSlide + 1);
  };
  const previousSlide = () => {
    goToSlide(currentSlide - 1);
  };

  return (
    <section
      class="group/carousel relative min-h-8 overflow-hidden text-white"
      aria-label="Carousel"
    >
      <div
        class="flex -translate-x-[--slide-offset] transition-transform duration-300 ease-out"
        style={{ "--slide-offset": `${currentSlide * 100}%` }}
      >
        {slides.map((slide, i) => (
          <img
            key={slide.src}
            src={slide.src}
            alt={`Slide ${currentSlide + 1} of ${lastSlide + 1}`}
            width={slide.width}
            height={slide.height}
            aria-hidden={i !== currentSlide}
          />
        ))}
      </div>
      <button
        class="push-down absolute left-2 top-1/2 -translate-y-1/2 select-none text-3xl hover:text-orchid"
        type="button"
        onClick={previousSlide}
        aria-label="Previous slide"
      >
        <Icon class="drop-shadow-stand-out" name="chevron-left" />
      </button>
      <button
        class="push-down absolute right-2 top-1/2 -translate-y-1/2 select-none text-3xl hover:text-orchid"
        type="button"
        onClick={nextSlide}
        aria-label="Next slide"
      >
        <Icon class="drop-shadow-stand-out" name="chevron-right" />
      </button>
      <ul class="absolute bottom-2 left-1/2 flex -translate-x-1/2 gap-2">
        {slides.map((_, i) => (
          <li key={i}>
            <button
              class={simpleCX(
                "push-down block select-none hover:text-orchid",
                i === currentSlide && "text-pink",
              )}
              type="button"
              onClick={() => {
                goToSlide(i);
              }}
              aria-label={`Go to slide ${i + 1}`}
              aria-current={i === currentSlide}
            >
              <Icon class="drop-shadow-stand-out" name="circle" />
            </button>
          </li>
        ))}
      </ul>
    </section>
  );
}

export default Carousel;

// src/lib/components/Carousel.svelte
<script lang="ts">
  import Icon from "$lib/components/Icon.svelte";
  import { onMount } from "svelte";

  interface Props {
    id: string;
    slides: { src: string; width: number; height: number }[];
  }

  let { id, slides }: Props = $props();

  let scroller = $state<HTMLElement>();
  let scrollerSlides = $state<HTMLElement[]>([]);

  // Keep track of the current slide
  let currentSlide = $state(0);

  onMount(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            currentSlide = scrollerSlides.indexOf(entry.target as HTMLElement);
          }
        });
      },
      {
        root: scroller,
        threshold: 0.6,
      },
    );

    scrollerSlides.forEach((slide) => {
      observer.observe(slide);
    });
    return () => {
      scrollerSlides.forEach((slide) => {
        observer.unobserve(slide);
      });
    };
  });

  // Manual controls
  function goToSlide(index: number) {
    scrollerSlides[index]?.scrollIntoView({
      behavior: "smooth",
      block: "center",
      inline: "center",
    });
  }

  function previousSlide() {
    goToSlide(currentSlide === 0 ? slides.length - 1 : currentSlide - 1);
  }

  function nextSlide() {
    goToSlide(currentSlide === slides.length - 1 ? 0 : currentSlide + 1);
  }
</script>

<section
  class="group/carousel text-offwhite aspect-4/3 relative overflow-hidden"
  aria-label="Carousel"
  aria-roledescription="carousel"
>
  <div
    bind:this={scroller}
    class="grid snap-x snap-mandatory auto-cols-[100%] grid-flow-col items-center overflow-x-auto overscroll-contain"
  >
    {#each slides as slide, i (slide.src)}
      <figure class="snap-center" bind:this={scrollerSlides[i]}>
        <img
          role="presentation"
          src={slide.src}
          width={slide.width}
          height={slide.height}
          loading="lazy"
          alt=""
        />
        <figcaption class="sr-only">
          Slide {i + 1} of {slides.length}
        </figcaption>
      </figure>
    {/each}
  </div>

  <button
    class="push-on-active hover:text-orchid center-y absolute left-0 select-none"
    type="button"
    aria-label="Slide anterior"
    aria-controls="{id}-slides-container"
    onclick={() => {
      previousSlide();
    }}
  >
    <Icon class="drop-shadow-contrast size-12" name="slide-left" />
  </button>
  <button
    class="push-on-active hover:text-orchid center-y absolute right-0 select-none"
    type="button"
    aria-label="Próximo slide"
    aria-controls="{id}-slides-container"
    onclick={() => {
      nextSlide();
    }}
  >
    <Icon class="drop-shadow-contrast size-12" name="slide-right" />
  </button>

  <div
    class="center-x absolute bottom-4 flex gap-2"
    role="tablist"
    aria-label="Navegação de slides"
  >
    {#each { length: slides.length }, i}
      <button
        class="push-on-active hover:text-orchid block select-none"
        type="button"
        role="tab"
        aria-label="Slide {i + 1}"
        aria-selected={i === currentSlide}
        aria-controls="{id}-slides-container"
        onclick={() => {
          goToSlide(i);
        }}
      >
        <Icon
          class="drop-shadow-contrast tablet:size-5 size-4"
          name={i === currentSlide ? "slide-dot-selected" : "slide-dot"}
        />
      </button>
    {/each}
  </div>
</section>
