// src/components/interactive/ProjectDetails.tsx
import { useStore } from "@nanostores/preact";
import { useEffect, useRef, useState } from "preact/hooks";
import { TECH_LABELS } from "../../constants";
import { $currentProject } from "../../store";
import { getProjectSlides, type ProjectImage } from "../../utils/projects";
import Icon from "../shared/Icon";
import Link from "../shared/Link";
import Carousel from "./Carousel";

function ProjectDetails() {
  const dialogRef = useRef<HTMLDialogElement>(null);

  const proj = useStore($currentProject);
  useEffect(() => {
    if (proj) {
      dialogRef.current?.showModal();
    } else {
      dialogRef.current?.close();
    }
  }, [proj]);

  const close = () => {
    $currentProject.set(undefined);
  };

  useEffect(() => {
    const dialog = dialogRef.current;
    if (dialog) {
      function handleClose() {
        close();
      }

      dialog.addEventListener("close", handleClose);
      return () => {
        dialog.removeEventListener("close", handleClose);
      };
    }
  }, [dialogRef]);

  const [slides, setSlides] = useState<ProjectImage[]>([]);
  useEffect(() => {
    if (proj) {
      setSlides(getProjectSlides(proj.id));
      return () => {
        setSlides([]);
      };
    }
  }, [proj]);

  const handleOutsideClick = (event: MouseEvent) => {
    if (event.target === dialogRef.current) {
      close();
    }
  };

  return (
    <dialog
      ref={dialogRef}
      class="z-20 max-h-[612px] max-w-[320px] overflow-hidden rounded-2xl bg-charcoal text-white shadow-elevation-high backdrop:bg-[rgba(0,0,0,0.9)] md:max-h-[896px] md:max-w-[640px] lg:grid lg:max-h-[540px] lg:max-w-[1300px]"
      onClick={handleOutsideClick}
    >
      {proj && (
        <>
          <button
            class="push-down absolute right-4 top-4 z-10 select-none text-2xl hover:text-orchid"
            type="button"
            onClick={close}
            aria-label="Fechar detalhes do projeto"
          >
            <Icon class="drop-shadow-stand-out" name="close" />
          </button>
          <div class="grid lg:grid-cols-[auto_1fr]">
            <Carousel slides={slides} />
            <article class="flex flex-col gap-4 overflow-auto px-6 pb-6 pt-4 lg:px-8 lg:pb-8">
              <h3 class="heading-md max-lg:text-center">{proj.title}</h3>
              <p class="mb-auto">{proj.description}</p>
              <ul
                class="flex flex-wrap justify-center gap-2"
                aria-label="Tecnologias usadas"
              >
                {proj.tech.map((tec) => (
                  <li
                    key={tec}
                    class="lg:flex lg:items-center lg:gap-2 lg:rounded-2xl lg:bg-slate lg:px-3 lg:py-2"
                    title={TECH_LABELS[tec]}
                  >
                    <Icon class="text-xl lg:text-lg" name={tec} />
                    <span class="cursor-default font-code font-bold text-gray max-lg:sr-only">
                      {TECH_LABELS[tec]}
                    </span>
                  </li>
                ))}
              </ul>
              <div class="flex items-center justify-between">
                <Link
                  class="text-2xl"
                  href={proj.repoLink}
                  description="Abrir repositório do projeto"
                  newTab
                >
                  <Icon name="github2" />
                </Link>
                <Link
                  class="flex items-center"
                  href={proj.link}
                  description="Abrir o site em uma nova aba"
                  newTab
                >
                  Visitar
                  <Icon class="text-xl" name="redirect" />
                </Link>
              </div>
            </article>
          </div>
        </>
      )}
    </dialog>
  );
}

export default ProjectDetails;

// src/lib/components/ProjectDetails.svelte
<script lang="ts" module>
  export const PROJECT_DETAILS_ID = "project-modal";
</script>

<script lang="ts">
  import Carousel from "$lib/components/Carousel.svelte";
  import Icon from "$lib/components/Icon.svelte";
  import Link from "$lib/components/Link.svelte";
  import { TECH_META } from "$lib/constants";
  import { activeProject } from "$lib/store";
  import clickaway from "$lib/utils/actions/clickaway.svelte";

  let open = $state(false);
  $effect(() => {
    open = !!$activeProject;
  });

  let dialog = $state<HTMLDialogElement>();
  $effect(() => {
    if (open) {
      dialog?.showModal();
    } else {
      dialog?.close();
      // Reset the global store when the dialog is closed
      $activeProject = undefined;
    }
  });
</script>

<dialog
  bind:this={dialog}
  id={PROJECT_DETAILS_ID}
  class="tablet:max-w-[640px] desktop:max-w-[1300px] bg-obsidian text-offwhite shadow-elevation desktop:h-[520px] starting:opacity-0 starting:scale-90 tablet:h-[calc(100dvh-8rem)] z-20 m-auto h-[calc(100dvh-4rem)] max-w-[320px] overflow-hidden rounded-2xl transition-[opacity,scale] duration-300 backdrop:bg-black/90"
  use:clickaway={{ ignoreSelf: true }}
  onclickaway={() => {
    open = false;
  }}
>
  {#if $activeProject}
    <button
      class="push-on-active hover:text-orchid absolute right-4 top-4 z-10 select-none"
      type="button"
      onclick={() => {
        open = false;
      }}
      aria-label="Fechar detalhes do projeto"
    >
      <Icon class="drop-shadow-contrast size-8" name="close" />
    </button>
    <div
      class="desktop:grid-cols-[auto_1fr] max-desktop:grid-rows-[auto_1fr] grid h-full"
    >
      <Carousel id="project" slides={$activeProject.previews} />
      <article
        class="desktop:px-8 desktop:pb-8 tablet:grid-cols-[auto_1fr_auto] tablet:grid-rows-[auto_1fr_auto] grid grid-cols-2 grid-rows-[auto_1fr_auto_auto] gap-4 overflow-auto px-6 pb-6 pt-4"
      >
        <h3 class="typo-heading-md max-desktop:text-center col-span-full">
          {$activeProject.title}
        </h3>
        <article class="**:[p]:mb-4 col-span-full mb-auto h-full overflow-auto">
          {@html $activeProject.description}
        </article>
        <div
          class="max-tablet:row-start-3 max-tablet:col-span-full tablet:col-start-2 tablet:place-self-start place-items-center"
        >
          <ul
            class="bg-charcoal flex flex-wrap justify-center gap-2 rounded-xl p-2"
            aria-label="Tecnologias usadas"
          >
            {#each $activeProject.technologies as tech (tech)}
              {@const { label, color } = TECH_META[tech]}
              <li title={label}>
                <Icon class="size-6" name={tech} {color} />
              </li>
            {/each}
          </ul>
        </div>
        <Link
          class="tablet:row-start-3 self-center"
          href={$activeProject.repository}
          aria-label="Abrir repositório do projeto"
          newTab
        >
          <Icon class="size-8" name="github" />
        </Link>
        <Link
          class="flex self-center justify-self-end"
          href={$activeProject.website}
          aria-label="Abrir o site em uma nova aba"
          newTab
        >
          Visitar
          <Icon class="size-6" name="redirect" />
        </Link>
      </article>
    </div>
  {/if}
</dialog>
